version: "3.8"

services:
  backend:
    build: .
    volumes:
      - .:/project
    ports:
      - 8000:8000
    image: django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    